name:                blog
version:             1.0.0
github:              "chungyc/site-blog"
homepage:            "https://blog.chungyc.org/"
license:             AllRightsReserved
author:              "Yoo Chung"
maintainer:          "dev@chungyc.org"
copyright:           "Copyright (C) 2023 Yoo Chung"

extra-source-files:
- README.md

synopsis:            Blog by Yoo Chung
category:            Personal

description:         Blog of Yoo Chung with random musings on recent events and random topics.

language: GHC2021

default-extensions:
- OverloadedStrings

dependencies:
- base

ghc-options:
- -Wall
- -Werror

library:
  source-dirs: src
  dependencies:
  - hakyll
  - bytestring
  - diagrams-core
  - diagrams-lib
  - diagrams-svg
  - pandoc
  - random
  - svg-builder

executables:
  site:
    main:                Site.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - blog
    - hakyll
    - clay
    - text

    # Work around https://github.com/sol/hpack/issues/303.
    when:
    - condition: false
      other-modules: Paths_blog
