# Some commonly used options have been documented as comments in this file.
# For advanced use and comprehensive documentation of the format, please see:
# https://docs.haskellstack.org/en/stable/yaml_configuration/

# Resolver to choose a 'specific' stackage snapshot or a compiler version.
# A snapshot resolver dictates the compiler version and the set of packages
# to be used for project dependencies.
resolver: lts-22.23

# User packages to be built.
packages:
- .

# Dependency packages to be pulled from upstream that are not in the resolver.
# These entries can reference officially published versions as well as
# forks / in-progress versions pinned to a git hash.
extra-deps:

  # Uses properties and media query functions not released yet.
  - git: https://github.com/sebastiaanvisser/clay.git
    commit: a59f9c6e56cb4870583b7b6bab0332f1d7a75b78
