name: Ormolu
permissions: read-all

on:
  push:
    paths:
      - '**.hs'
      - '**.lhs'
  pull_request:
    paths:
      - '**.hs'
      - '**.lhs'      

jobs:
  ormolu:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v5
      - uses: haskell-actions/run-ormolu@v17
        with:
          respect-cabal-files: false
          extra-args: '-o -XGHC2021 -o -XOverloadedStrings'
